"""Rule alignment monitor - deep verification that the student's env produces
games consistent with the teacher's tournament server.

Two modes of check:

(A) Quick check (used during training every K iters):
    Take a self-play trajectory generated by GameEnv, recompute the resulting
    final_score per player using teacher_score, and verify it matches the
    env's own compute_final_score within 0.5 points. (Internal consistency.)

(B) Deep check (used manually or periodically):
    Boot teacher's game.py server, replay every move of a self-play game
    on it, and verify:
      - every move is accepted by the server
      - the final scores match within 1 point
      - the winner (if any) matches

If any check fails, the monitor returns alignment_ok=False; the trainer
writes a RULE_ALIGNMENT_FAILED flag and pauses.
"""

from __future__ import annotations

import json
import os
import socket
import subprocess
import sys
import threading
import time
from typing import Any, Dict, List, Optional, Tuple

NEXUS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
TEACHER_DIR = os.path.join(
    NEXUS_DIR, "RLChineseCheckers", "multi system single machine minimal"
)
if NEXUS_DIR not in sys.path:
    sys.path.insert(0, NEXUS_DIR)

from core import teacher_score as ts
from core.action_space import decode_action
from core.board import HexBoard
from core.game_env import GameEnv

HOST, PORT = "127.0.0.1", 50555


# ── (A) Quick consistency check ──────────────────────────────────


def quick_consistency_check(env_after_game: GameEnv,
                            sums_per_player: List[float],
                            tolerance: float = 0.5) -> Dict[str, Any]:
    """Verify that init_potential[p] + sums[p] == pin_score(p) + dist_score(p)
    for every player. This is the telescoping invariant."""
    failures = []
    for p in range(env_after_game.num_players):
        color = env_after_game.colors[p]
        pins = env_after_game.board.count_in_goal(env_after_game.pieces[p], color)
        dist = env_after_game.board.sum_distances_to_goal(env_after_game.pieces[p], color)
        expected = ts.pin_goal_score(pins) + ts.distance_score(dist)
        actual = env_after_game.init_potential(p) + sums_per_player[p]
        if abs(actual - expected) > tolerance:
            failures.append({
                "player": p, "color": color,
                "expected": expected, "actual": actual,
                "diff": actual - expected,
            })
    return {
        "type": "telescoping_consistency",
        "alignment_ok": not failures,
        "failures": failures,
        "num_players": env_after_game.num_players,
    }


# ── (B) Deep check - replay on teacher's server ──────────────────


def _rpc(payload: Dict[str, Any]) -> Dict[str, Any]:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(10.0)
    try:
        s.connect((HOST, PORT))
    except Exception as e:
        return {"ok": False, "error": str(e)}
    s.sendall(json.dumps(payload).encode("utf-8"))
    chunks = []
    while True:
        try:
            data = s.recv(1_000_000)
            if not data:
                break
            chunks.append(data)
            try:
                json.loads(b"".join(chunks).decode("utf-8"))
                break
            except json.JSONDecodeError:
                continue
        except socket.timeout:
            break
    s.close()
    try:
        return json.loads(b"".join(chunks).decode("utf-8"))
    except Exception:
        return {"ok": False, "error": "no-response"}


def _start_server() -> Optional[subprocess.Popen]:
    proc = subprocess.Popen(
        ["python3", "game.py"],
        cwd=TEACHER_DIR,
        stdin=subprocess.PIPE,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    time.sleep(1.5)
    proc.stdin.write(b"create\n")
    proc.stdin.flush()
    for _ in range(40):
        sr = _rpc({"op": "status"})
        if sr.get("ok") and len(sr.get("games", [])) >= 1:
            return proc
        time.sleep(0.25)
    return proc


def _stop_server(proc: subprocess.Popen):
    try:
        proc.terminate()
        proc.wait(timeout=3)
    except Exception:
        proc.kill()


def replay_trajectory_on_server(
    trajectory: List[Dict],
    seat_colors: List[str],
    timeout_sec: float = 90.0,
) -> Dict[str, Any]:
    """Replay an N-player self-play trajectory on the teacher's actual server.

    The trajectory must include for every entry: 'player' (seat index),
    'action' (encoded), and the action must be applied in turn order.

    Returns dict with: alignment_ok, moves_replayed, server_final_state,
    student_final_score (recomputed), discrepancies.
    """
    N = len(seat_colors)

    # Reconstruct piece positions step-by-step in a local nexus env
    # (so we can derive (pin_id_in_server, to_index) from the encoded action).
    board = HexBoard()
    env = GameEnv(board, num_players=N)
    env.reset(num_players=N, colors=seat_colors)

    proc = _start_server()
    if not proc:
        return {"alignment_ok": False, "error": "server-start-failed"}

    stop_evt = threading.Event()

    # Spawn N "replay clients" - they JOIN, send START, and on each turn read
    # the next move from the trajectory and POST it.
    moves_by_seat: List[List[Tuple[int, int]]] = [[] for _ in range(N)]
    for entry in trajectory:
        seat = entry["player"]
        action = entry["action"]
        piece_id, dest = decode_action(action)
        # Server uses pin_id of THIS seat at the time of the move; we'll
        # track positions to map piece_id (sorted index) to server pin_id.
        moves_by_seat[seat].append((piece_id, dest))

    # Server-side pin_ids are 0..9 and stay fixed; teacher's order is the
    # initial sort of axial_of_colour(colour). Our nexus env's pieces[seat]
    # is also a sorted list - but it stays sorted by cell index (changes as
    # pieces move). Server pin_ids never change. So we cannot directly map
    # piece_id (== sorted index) to server pin_id from our trajectory.
    #
    # To match, we maintain a parallel server-side "pin position list" indexed
    # by pin_id, and use the server's get_legal_moves response to find the
    # pin_id corresponding to the cell-index our nexus env has selected.
    server_pin_positions: Dict[str, List[int]] = {
        c: list(sorted(board.axial_of_colour_indices(c)
                       if hasattr(board, "axial_of_colour_indices")
                       else sorted(board.start_zones[c])))
        for c in seat_colors
    }
    # Just to be safe: derive the sorted starting pin lists like teacher does
    # via board.start_zones (which we verified matches teacher's axial_of_colour).
    server_pin_positions = {
        c: sorted(board.start_zones[c])[:10] for c in seat_colors
    }

    # Connect N clients
    client_data: List[Dict[str, Any]] = []
    join_lock = threading.Lock()
    join_done = threading.Event()
    started_lock = threading.Lock()

    def join_and_register(seat: int, name: str) -> Optional[Dict[str, Any]]:
        r = _rpc({"op": "join", "player_name": name})
        if not r.get("ok"):
            return None
        return {
            "seat": seat,
            "game_id": r["game_id"],
            "player_id": r["player_id"],
            "colour": r["colour"],
        }

    # Sequentially join (so colors are assigned in order matching seat_colors)
    for seat, c in enumerate(seat_colors):
        info = join_and_register(seat, f"REP{seat}")
        if info is None or info["colour"] != c:
            _stop_server(proc)
            return {
                "alignment_ok": False,
                "error": f"seat {seat} expected color {c}, got {info and info['colour']}",
            }
        client_data.append(info)

    # Wait until N players visible
    game_id = client_data[0]["game_id"]
    for _ in range(60):
        st = _rpc({"op": "get_state", "game_id": game_id}).get("state", {})
        if len(st.get("players", [])) >= N:
            break
        time.sleep(0.1)

    # All START
    for c in client_data:
        _rpc({"op": "start", "game_id": game_id, "player_id": c["player_id"]})
    # Wait PLAYING
    for _ in range(60):
        st = _rpc({"op": "get_state", "game_id": game_id}).get("state", {})
        if st.get("status") == "PLAYING":
            break
        time.sleep(0.1)

    # Apply moves in trajectory order
    moves_replayed = 0
    discrepancies = []
    for entry in trajectory:
        seat = entry["player"]
        client = client_data[seat]
        # Wait until it's this seat's turn
        for _ in range(40):
            st = _rpc({"op": "get_state", "game_id": game_id}).get("state", {})
            if st.get("current_turn_colour") == client["colour"]:
                break
            if st.get("status") == "FINISHED":
                break
            time.sleep(0.05)
        st = _rpc({"op": "get_state", "game_id": game_id}).get("state", {})
        if st.get("status") == "FINISHED":
            break

        piece_id_local, dest = decode_action(entry["action"])
        # Fetch server's legal_moves for this seat to map piece_id_local
        lr = _rpc({
            "op": "get_legal_moves",
            "game_id": game_id,
            "player_id": client["player_id"],
        })
        legal = lr.get("legal_moves", {})

        # Map: nexus's piece_id is the sorted index in env.pieces[seat] before
        # this move. Server's pin_id is fixed - figure out which server pin_id
        # currently sits at the same cell as nexus's piece.
        nexus_piece_pos = env.pieces[seat][piece_id_local]
        # Find server pin_id at this cell. server_pin_positions[colour] tracks.
        colour = client["colour"]
        server_pin_id = None
        for spid, pos in enumerate(server_pin_positions[colour]):
            if pos == nexus_piece_pos:
                server_pin_id = spid
                break
        if server_pin_id is None:
            discrepancies.append({
                "step": moves_replayed,
                "seat": seat,
                "error": f"could not locate server pin for nexus pos {nexus_piece_pos}",
            })
            break
        # Verify the destination is in the server's legal-move list for this pin
        legal_dests = legal.get(str(server_pin_id), [])
        if dest not in legal_dests:
            discrepancies.append({
                "step": moves_replayed,
                "seat": seat,
                "server_pin": server_pin_id,
                "dest": dest,
                "server_legal": legal_dests[:8],
            })
            break

        # POST move
        mv = _rpc({
            "op": "move", "game_id": game_id,
            "player_id": client["player_id"],
            "pin_id": server_pin_id, "to_index": dest,
        })
        if not mv.get("ok"):
            discrepancies.append({"step": moves_replayed, "rpc_error": mv.get("error")})
            break

        # Update local env + server pin tracker
        env.step(entry["action"])
        server_pin_positions[colour][server_pin_id] = dest
        moves_replayed += 1

        if mv.get("status") in ("WIN", "DRAW"):
            break

    # Read final state
    final = _rpc({"op": "get_state", "game_id": game_id}).get("state", {})

    # Compare per-player final scores
    score_match = True
    score_diffs = []
    for c in client_data:
        seat = c["seat"]
        sc = next(
            (p.get("score") for p in final.get("players", [])
             if p["player_id"] == c["player_id"]),
            None,
        )
        if sc is None:
            score_match = False
            score_diffs.append({"seat": seat, "error": "no server score"})
            continue
        student_score = env.compute_final_score(seat)
        # Server's final_score includes time + move; we compare without time
        # (since student virtual-time != server real-time).
        student_partial = (
            ts.move_score(env.player_move_counts[seat])
            + ts.pin_goal_score(env.board.count_in_goal(env.pieces[seat], env.colors[seat]))
            + ts.distance_score(env.board.sum_distances_to_goal(env.pieces[seat], env.colors[seat]))
        )
        server_partial = (
            sc.get("move_score", 0)
            + sc.get("pin_goal_score", 0)
            + sc.get("distance_score", 0)
        )
        if abs(student_partial - server_partial) > 1.5:
            score_match = False
            score_diffs.append({
                "seat": seat, "color": c["colour"],
                "student_partial": student_partial,
                "server_partial": server_partial,
                "diff": student_partial - server_partial,
            })

    _stop_server(proc)

    alignment_ok = (
        not discrepancies
        and score_match
        and moves_replayed > 0
    )
    return {
        "alignment_ok": alignment_ok,
        "moves_replayed": moves_replayed,
        "moves_total": len(trajectory),
        "discrepancies": discrepancies,
        "score_diffs": score_diffs,
        "type": "deep_replay",
    }
