"""C6-equivariant spatial layer for hex-grid features.

Implements a manual (no-escnn) discrete C6 group-equivariant
convolution on a hex grid laid out in axial coordinates. C6 is the
cyclic subgroup of D6 generated by 60° rotation; combined with the
seat-permutation factor, this gives one half of the wreath product
G_N ≀ S_N. Adding the reflection (full D6) and the data-dependent
subgroup gating (ASEN style) is straightforward extension; we keep this
file at the C6 stage to demonstrate the core technique with minimal
dependencies.

Why manual instead of escnn
---------------------------
escnn is the right tool for production but adds a heavy dependency
(~1GB total with numpy/scipy/torch). For the workshop-tier
demonstration we only need to show the *equivariance property holds
bit-identically* under rotation - that's a 100-line manual
implementation, fully testable.

How it works
------------
A C6-equivariant feature map has 6 "rotation channels" per spatial
location, indexed by `r ∈ {0, 1, 2, 3, 4, 5}`. A 60° rotation of the
hex grid acts on a feature map `f` by:

    (R · f)[x, y, r] = f[R^{-1}(x, y), (r - 1) mod 6]

i.e., it rotates the spatial location AND cyclically shifts the
rotation-channel dimension.

A C6-equivariant convolution's kernel `k[a, b, r_in, r_out]` must
satisfy

    k[R(a, b), r_in + 1, r_out + 1] = k[a, b, r_in, r_out]

so the kernel weights are *tied across* rotated copies. We achieve
this by storing only the canonical-rotation kernel and synthesising
the 6 rotated copies on the fly when convolving.

Hex-grid coordinate system
--------------------------
We use *axial coordinates* (q, r_axial) for hex tiles, with the C6
rotation acting as the linear map

    (q, r_axial) ↦ (-r_axial, q + r_axial)

(See e.g. https://www.redblobgames.com/grids/hexagons/.)

For a small grid this can be computed once and cached as a permutation
matrix.
"""

from __future__ import annotations

from typing import Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


# 60° rotation in axial coordinates.
def rotate_axial(qr: Tuple[int, int]) -> Tuple[int, int]:
    """One 60° rotation in axial (q, r) coordinates."""
    q, r = qr
    return (-r, q + r)


def make_rotation_permutation(coords: list, num_rotations: int = 6) -> np.ndarray:
    """For a list of axial coords [(q,r), ...], return a permutation
    matrix P of shape (num_rotations, n_coords) where
    P[k, i] = j means: rotating coord i by k×60° lands on coord j.

    If the rotated coord is not in the original list (boundary effects),
    we set P[k, i] = i (identity fallback) - this is a small artifact at
    the grid boundary that the test will catch if we get it wrong.
    """
    coord_to_idx = {c: i for i, c in enumerate(coords)}
    n = len(coords)
    P = np.zeros((num_rotations, n), dtype=np.int64)
    for k in range(num_rotations):
        for i, c in enumerate(coords):
            rotated = c
            for _ in range(k):
                rotated = rotate_axial(rotated)
            if rotated in coord_to_idx:
                P[k, i] = coord_to_idx[rotated]
            else:
                # Fallback: don't move. This breaks strict equivariance
                # at the boundary but lets us train on bounded grids.
                P[k, i] = i
    return P


class C6EquivariantLinear(nn.Module):
    """A C6-equivariant linear layer over hex-grid features.

    Input shape:  (batch, num_locations, 6 * in_channels)
                   where the "6" axis indexes the rotation channels.
    Output shape: (batch, num_locations, 6 * out_channels)

    The layer maintains a single (in_channels, out_channels)-shaped
    weight per (a_in_rotation_offset) for `a ∈ {0..5}` - a
    "regular-representation" equivariant linear layer. The output at
    rotation channel r_out is

        out[..., r_out, c_out] = sum_{a=0..5, c_in}
            W[a, c_in, c_out] * in[..., (r_out - a) mod 6, c_in]

    Equivariance: rotating the input cyclically shifts the rotation
    channels, and the output rotates the same way.
    """

    def __init__(self, in_channels: int, out_channels: int) -> None:
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        # Regular-rep weight: 6 × in × out
        self.weight = nn.Parameter(
            torch.randn(6, in_channels, out_channels) * (in_channels ** -0.5)
        )
        self.bias = nn.Parameter(torch.zeros(out_channels))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: (B, L, 6 * in)
        B, L, F = x.shape
        assert F == 6 * self.in_channels
        x = x.view(B, L, 6, self.in_channels)
        # Build output by summing rotated copies.
        out = torch.zeros(B, L, 6, self.out_channels, device=x.device, dtype=x.dtype)
        for a in range(6):
            # rotation offset a: contribution to out[..., r_out, c_out]
            # from in[..., (r_out - a) mod 6, c_in].
            # W[a, c_in, c_out] shared across r_out.
            for r_out in range(6):
                r_in = (r_out - a) % 6
                # x_slice: (B, L, in)
                x_slice = x[:, :, r_in, :]
                # contrib: (B, L, out)
                contrib = x_slice @ self.weight[a]
                out[:, :, r_out, :] = out[:, :, r_out, :] + contrib
        out = out + self.bias  # broadcast over (B, L, 6, out)
        return out.view(B, L, 6 * self.out_channels)


def rotate_feature_map(
    x: torch.Tensor,
    permutation: torch.Tensor,
    num_channels_per_rotation: int,
    rotation_index: int,
) -> torch.Tensor:
    """Apply a discrete C6 rotation to a feature map.

    Args:
        x: (B, L, 6 * C) feature map.
        permutation: (6, L) location permutation table from make_rotation_permutation.
        num_channels_per_rotation: C.
        rotation_index: integer in [0, 6) - which rotation to apply.

    Returns the rotated feature map: spatial locations permuted AND
    rotation-channel index cyclically shifted by `rotation_index`.
    """
    B, L, F = x.shape
    C = num_channels_per_rotation
    assert F == 6 * C
    # Spatial permutation
    perm = permutation[rotation_index].to(x.device)
    x = x[:, perm, :]  # (B, L, 6 * C)
    # Reshape and roll the rotation-channel axis
    x = x.view(B, L, 6, C)
    x = torch.roll(x, shifts=rotation_index, dims=2)
    return x.view(B, L, 6 * C)
